export interface updateASurveillanceResource{
    
    weight:number;
    hemoglobin:number;
    lymphocytes:number;
    segmented:number;
    monocytes:number;
    mvc:number;
    mch:number;
    leukocytes:number;
    erythrocytes:number;
    glucose:number;
    cholesterol:number;
    urea:number;
    creatinine:number;
    density:number;
    ph:number;
    protein:number;
    ketone:number;
    urobilinogen:number;
    bilirubin:number;
    nitrite:number;
    crystals:number;
    sugar:number;
    urineAppearance:string;
    urineColor:string;
    planCalories:number;
    consumedCalories:number;
    appetite:string;
    pain:string;
    hematies:number;
    otherSymptoms:string;
    imc:number;
}